# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8972eea16412f0d5119140852aedbc6785fbcf61a45c1355d4521c5b6d3740c1ded9005591e6f896bb3edc26d9cfb4f6cd7506e59ca9c5c1b751699ed8170f32

test:
  secret_key_base: e1c804b56964bfcd34d677cd208631919ed75aa92dedccfad35df957fcaf0c6068ffb54bc72696ec6c6f6d7cf3729e69ebd0a5a3f6f449050357ccb9bc9e2220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
